## File I/O with Numpy



Saving and loading data from disk



In [3]:
import numpy as np
arr = np.arange(10)
np.save('some_array', arr)
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Saving multiple arrays and compressing them



In [11]:
np.savez('array_archive.npz', a=arr, b=arr)
x = np.load('array_archive.npz')
x['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Random number generation



Numpy contains a number of probability distributions



In [12]:
samples = np.random.normal(0, 1, (4,4))
samples

array([[-0.61402143, -1.33548473, -0.00311146, -0.2406352 ],
       [ 0.45929834, -0.47876499, -0.8586241 , -1.26698214],
       [ 1.09175499,  0.02328325, -0.09353014,  1.29546524],
       [-0.49234998, -0.71758151,  1.12832772, -0.76607812]])

Partial list of `np.random` functions
![img](images/numpy_random.png)



## Example: Random walk



> A random walk is a stochastic process that describes a path that consists of a succession of random steps on some mathematical space such as the integers. An elementary example of a random walk is the random walk on the integer number line, $\mathbb {Z}$ , which starts at 0 and at each step moves +1 or −1 with equal probability1. Simulate a random walk of 1000 steps with two implementations (one with loops and one with Numpy)

1.  What is the farthest position reached during the random walk?
2.  How long did it take to cross step 10 in either direction (*first crossing time*)?



In [39]:
import random

def randomWalkWithLoop(nsteps=1000):
    """Simulate a 1D random walk."""
    position = 0
    walk = [position]
    for step in range(nsteps):
        stepping = 1 if random.randint(0, 1) else -1
        position += stepping
        walk.append(position)
    return walk

def randomWalkWithArrays(nsteps=1000):
    """Simulate a 1D random walk."""
    draws = np.random.randint(0, 2, nsteps)
    steps = np.where(draws > 0, 1, -1)
    walk = steps.cumsum()
    return walk

#walk = randomWalkWithArrays()
#import matplotlib.pyplot as plt
#plt.plot(walk);
np.where(abs(walk) >= 10)[0][0]

55

## Real-world application of a random walk model



![img](images/riddle1.png)



![img](images/riddle2.png)



### Model implementation



We will assume an initial volume of 200x200x1 meters, and a hypothetical spill of 25 kg. The safe concentration is 0.005 mg/l, and the displacement of the spill is given by
$$\Delta x = U (p+1) \left( \frac{Z_{0}+\Delta z}{d} \right)^{p} dt + f_{x} \alpha$$

$$\Delta y = V (p+1) \left( \frac{Z_{0}+\Delta z}{d} \right)^{p} dt + f_{y} \beta$$

$$\Delta z = f_{z} \gamma$$

where $U=0.01$m/s, $V=0.01$m/s, $p=0.192$, $Z{0}=8.6$m, $d=1.0$m. How long will it take for the concentration to reach safe levels? Assume a time step of 60s.

